commented out debugging steps; uncommented dbt build

diff --git a/.github/workflows/dbt_v1.8.6_bigquery_build_full_refresh.yml b/.github/workflows/dbt_v1.8.6_bigquery_build_full_refresh.yml
--- a/.github/workflows/dbt_v1.8.6_bigquery_build_full_refresh.yml
+++ b/.github/workflows/dbt_v1.8.6_bigquery_build_full_refresh.yml
@@ -72,35 +72,27 @@ jobs:
         run: |
           echo "${{ secrets.TUVA_BIGQUERY_TOKEN }}" | base64 --decode > ./ci_testing/creds.json
 
-      - name: Validate credentials file
-        run: |
-          cat ./ci_testing/creds.json | jq . || echo "Invalid JSON format"
+#      - name: Validate credentials file
+#        run: |
+#          cat ./ci_testing/creds.json | jq . || echo "Invalid JSON format"
 
-      - name: Display credentials file
-        run: cat ./ci_testing/creds.json
-
-#      - name: List profiles directory
-#        run: ls -la ./ci_testing/profiles/bigquery
-#
-#      - name: Display profiles.yml contents
-#        run: cat ./ci_testing/profiles/bigquery/profiles.yml
 
       - name: dbt-deps
         run: dbt deps --profiles-dir ./profiles/bigquery
         working-directory: ci_testing
 
-      - name: Verify profiles.yml
-        run: |
-          cat ./ci_testing/profiles/bigquery/profiles.yml
-          ls -R ./ci_testing/profiles/
+#      - name: Verify profiles.yml
+#        run: |
+#          cat ./ci_testing/profiles/bigquery/profiles.yml
+#          ls -R ./ci_testing/profiles/
 
       - name: dbt-debug
         run: dbt debug --profiles-dir ./ci_testing/profiles/bigquery
 
-#      - name: dbt-build
-#        run: |
-#          dbt build --full-refresh --profiles-dir ./ci_testing/profiles/bigquery --vars '{"input_database":"dev_ci_testing","input_schema":"input_layer","clinical_enabled":true,"claims_enabled":true}'
-#        working-directory: ci_testing
+      - name: dbt-build
+        run: |
+          dbt build --full-refresh --profiles-dir ./ci_testing/profiles/bigquery --vars '{"input_database":"dev_ci_testing","input_schema":"input_layer","clinical_enabled":true,"claims_enabled":true}'
+        working-directory: ci_testing
 
       - name: Get the result
         if: ${{ always() }}
